[workspace]
resolver = "3"
members = ["cli", "runtime", "common", "core"]
exclude = ["hello"]

[workspace.dependencies]
common = { path = "common" }
runtime = { path = "runtime" }
core = { path = "core" }
