[package]
name = "runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
wasmtime = "15.0"
wasmtime-wasi = "15.0"
common = { path = "../common" }
qyvol-core = { path = "../core" }
thiserror = "1.0"
reqwest = { version = "0.11", features = ["blocking"] }
tokio = { version = "1.0", features = ["rt"] }
indicatif = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"