name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Instalar Rust estable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache de dependencias
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Verificar que compile
      run: cargo check --workspace --all-targets

    - name: Formato del código
      run: cargo fmt --check

    - name: Linter Clippy
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings

    - name: Ejecutar pruebas
      run: cargo test --workspace --all-targets --all-features

    - name: Auditoría de seguridad
      run: cargo install cargo-audit && cargo audit

